config/routes.rb
Rails.application.routes.draw do

  root "posts#index"

  resources :posts

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to edit_post_path(@post), notice: "Updated #{@post.title}"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to '/'
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_path, notice: "Updated #{@post.title}"
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloggingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class:"form-control" %>
</div>
<div class="form-group">
  <%= f.label :category %>
  <%= f.collection_select(:category, Category.all, :id, :name) %>
</div>
  <%= f.submit f.object.new_record? ? "Create Post" : "Update Post", class:"btn btn-success btn-sm" %>
<% end %>

app/views/posts/edit.html.erb
<%= link_to "Homepage", "/" %>

<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Best Blog</h1>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Category</th>
    <td></td>
  </tr>
  <% @posts.each do |post| %>
  <tr>
    <td><a href="/posts/<%= post.id %>"><%= post.title %></a></td>
    <td><%= post.content %></td>
    <td><%= post.category.name %></td>
    <td><%= link_to "Delete", "/posts/#{post.id}", method: :delete, class:"btn-sm btn-danger" %></td>
  </tr>
  <% end %>
</table>

<%= link_to "New Post", new_post_path, class:"btn btn-sm btn-primary" %>

app/views/posts/new.html.erb
<%= link_to "Homepage", "/" %>

<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<%= link_to "Homepage", "/" %>

<h1>Show</h1>

<p>
  <%= @post.title %>
</p>

<p>
  <%= @post.content %>
</p>

<%= link_to "Edit", edit_post_path(@post) %>